library ieee;
use ieee.std_logic_1164.all;
use ieee.numeric_std.all;

entity freq_divbyfrac is
    port (
        clk     : in  std_logic;   -- Input clock signal
        rst_n   : in  std_logic;   -- Active low reset
        clk_div : out std_logic    -- Fractionally divided clock output
    );
end entity freq_divbyfrac;

architecture rtl of freq_divbyfrac is
    -- Counter for 7 source clock cycles (0..6)
    signal cnt      : integer range 0 to 6 := 0;
    -- Intermediate signals for double-edge generation
    signal pos_high : std_logic := '0';
    signal neg_high : std_logic := '0';
begin

    -------------------------------------------------------------------------
    -- Rising-edge process: counter and positive-edge controlled signal
    -------------------------------------------------------------------------
    process (clk, rst_n)
    begin
        if rst_n = '0' then
            cnt      <= 0;
            pos_high <= '0';
        elsif rising_edge(clk) then
            -- Modulo-7 counter
            if cnt = 6 then
                cnt <= 0;
            else
                cnt <= cnt + 1;
            end if;

            -- Generate a pulse that is high for 2 source clock cycles
            -- starting at count 0.
            if cnt = 0 then
                pos_high <= '1';
            elsif cnt = 2 then
                pos_high <= '0';
            end if;
        end if;
    end process;

    -------------------------------------------------------------------------
    -- Falling-edge process: negative-edge controlled signal
    -------------------------------------------------------------------------
    process (clk, rst_n)
    begin
        if rst_n = '0' then
            neg_high <= '0';
        elsif falling_edge(clk) then
            -- Generate a pulse that is high for 2 source clock cycles
            -- starting at the half-cycle point when cnt = 3.
            if cnt = 3 then
                neg_high <= '1';
            elsif cnt = 5 then
                neg_high <= '0';
            end if;
        end if;
    end process;

    -------------------------------------------------------------------------
    -- OR combination: final clock with period 3.5 source cycles
    --   High periods: 0..2 cycles, 3.5..5.5 cycles
    --   Low periods:  2..3.5 cycles, 5.5..7 cycles
    --   Consistent 3.5-cycle output period, generated by double-edge technique.
    -------------------------------------------------------------------------
    clk_div <= pos_high or neg_high;

end architecture rtl;